name: Fetch JSON and Commit

on:
  schedule:
    - cron: '0,30 * * * *'  # Runs at the start and middle of every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch JSON file
      run: |
        import requests
        response = requests.get('https://api.raydium.io/v2/sdk/liquidity/mainnet.json', timeout=600)
        with open('mainnet.json', 'wb') as file:
          file.write(response.content)
      timeout-minutes: 10

    - name: Split JSON file
      run: |
        import os
        import json

        max_size = 95 * 1024 * 1024  # 95 MB in bytes
        file_prefix = 'mainnet'
        file_suffix = 1

        with open('mainnet.json', 'r') as file:
          data = json.load(file)

        current_file_data = []
        current_file_size = 0

        for item in data:
          item_size = len(json.dumps(item).encode('utf-8'))
          if current_file_size + item_size > max_size:
            output_file = f'{file_prefix}_{file_suffix}.json'
            with open(output_file, 'w') as file:
              json.dump(current_file_data, file)
            current_file_data = []
            current_file_size = 0
            file_suffix += 1
          current_file_data.append(item)
          current_file_size += item_size

        if current_file_data:
          output_file = f'{file_prefix}_{file_suffix}.json'
          with open(output_file, 'w') as file:
            json.dump(current_file_data, file)

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.json
        git commit -m 'Update JSON files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
